config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "main#home", as: :root
  # Pdfjs gem route configuration
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  # Administrate gem route configuration
  namespace :admin do
      # CKEditor gem route configuration
      mount Ckeditor::Engine => '/ckeditor'
      resources :users
      resources :articles
      resources :albums
      resources :pdfs
      resources :events
      resources :links
      resources :texts
      resources :pictures
      resources :slideshows
      root to: "users#index", as: :root
      post '/users/send_invitation(/:name)(/:email)', to: "users#send_invitation", as: :invitation
  end
  # Devise gem route configuration
  devise_for :users, controllers: {registrations: 'users/registrations'}
  match 'users/:id' => 'user_space#destroy', :via => :delete, :as => :admin_destroy_user
  get '/adherents', to: "user_space#main", as: :user_space
  get '/adherents/user', to: "user_space#simple_user_space", as: :simple_user_space
  get '/adherents/admin', to: "user_space#admin_space", as: :admin_space
  get '/privacy', to: "privacy#privacy", as: :privacy
  post '/contact_us(/:name)(/:email)(/:message)', to: "main#contact_us", as: :contact_us

end

app/controllers/user_space_controller.rb
class UserSpaceController < ApplicationController
  before_action :set_current_user

  def main
    @private_albums = Album.where(private: true)
    @pdfs = Pdf.all
    @form = Link.find_by(title: "Questionnaire")
    if Pdf.where(latest: true).empty?
      @on_top_pdf = Pdf.all.order(:id).last
    else
      @on_top_pdf = Pdf.where(latest: true).order(:id).last
    end
    @picture_form = Picture.find_by(title:"questionnaire")
    @text_form = Text.find_by(title:"questionnaire")
  end

  def admin_space
    #Nothing special to do here, just render the view
  end

  def simple_user_space
    #Nothing special to do here, just render the view
  end

  def set_current_user
    if current_user
      session[:user] = User.find(current_user.id)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
      flash[:danger] = 'Compte supprimé'
      redirect_to root_url
    end
  end

end

app/views/user_space/_admin_space.erb
<head>
  <%= stylesheet_link_tag 'user_space', media: 'all', 'data-turbolinks-track': 'reload' %>
  <title>Espace administrateur du site Vital'Marche</title>
</head>

<nav class="navbar navbar-default navbar-fixed green no-background bootsnav">
  <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
      <em class="fa fa-bars"></em>
    </button>
    <a class="navbar-brand" href="#brand">

      <img class="logo logo-display m-top-10" alt="Logo Vital'Marche"  <%= image_tag "logo.png" %>
      <img class="logo logo-scrolled"  alt="Logo Vital'Marche"  <%= image_tag "logo.png" %>

    </a>
  </div>
  <!-- End Header Navigation -->

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-menu">
    <ul class="nav navbar-nav navbar-right blue" data-in="fadeInDown" data-out="fadeOutUp">
      <li> <%= link_to "RETOUR ACCUEIL", root_path %>
        <% if user_signed_in? %>
        <li class="nav-item hvr-grow">
          <%= link_to raw('<i class="fas fa-power-off"></i></i> <span class="d-md-none"></span>'), destroy_user_session_path, class: "nav-link-danger", title: "Déconnexion", method: :delete %>
        </li>
      <% end %>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>


</nav>



<section class="user_space-slide">
  <!--    <div class="overlay"></div>-->
  <div class="container ">
    <div class="row bck_layer">
      <div class="user_space_buttons">
        <div class="main_home user_space_text_div col-md-12">
          <div>
            <h1 class="user_space_text">Espace administrateur</h1>
          </div>
        </div>
        <div class="main_home col-md-12">
          <div class="user_space_button col-md-6">
            <%= link_to "Tableau de bord", admin_users_path, class: "btn btn-outline-primary col-md-12" %>
          </div>
          <div class="user_space_button col-md-6">
            <%= link_to "Gérer les albums", admin_albums_path, class: "btn btn-outline-primary col-md-12" %>
          </div>
        </div>
      </div>
    </div><!--End off row-->
  </div><!--End off container -->
</section> <!--End off Home Sections-->

app/views/user_space/_simple_user_space.erb
<body data-spy="scroll" data-target=".navbar-collapse">
<div class="culmn">
  <nav class="navbar navbar-default navbar-fixed green no-background bootsnav">
    <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
          <em class="fas fa-ellipsis-v"></em>
        </button>
        <div class="navbar-brand">
          <img class="logo logo-display m-top-10" alt="Logo Vital'Marche" <%= image_tag "logo.png" %>
          <img class="logo logo-scrolled" alt="Logo Vital'Marche" <%= image_tag "logo.png" %>
        </div>
      </div>

      <div class="collapse navbar-collapse" id="navbar-menu">
        <ul class="nav navbar-nav navbar-right blue" data-in="fadeInDown" data-out="fadeOutUp">
          <li><a href="#planning">PLANNING</a></li>
          <li><a href="#pdf">GAZETTES</a></li>
          <li><a href="#form">QUESTIONNAIRE</a></li>
          <li><a href="#photo-gallery">GALERIE</a></li>
          <li> <%= link_to "RETOUR ACCUEIL", root_path, data: {turbolinks: false} %> </li>
          <% if user_signed_in? %>
            <li class="nav-item hvr-grow">
              <%= link_to raw('<i class="fas fa-power-off"></i> <span class="d-md-none"></span>'), destroy_user_session_path, class: "nav-link-danger", title: "Déconnexion", method: :delete %>
            </li>
          <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <section class="user_space-slide page">
    <div class="container ">
      <div class="row bck_layer">
        <div class="col-xs-12 vertical-center">
          <div class="main_home user_space_text_div text-center">
            <div>
              <h1 class="user_space_text">Bienvenue <b><%= session[:user].name %></b></h1>
            </div>
            <div>
              <% if session[:user] %>
                <% if session[:user].email == 'contactvitalmarche@gmail.com' %>
                  <div class="col-xs-12 m-top-100">
                    <%= link_to "Espace administrateur", admin_users_path, class: "btn btn-outline-primary to_fill_text" %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="planning" class="page">
    <br>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="about_content">
            <h3 class="text-blue">PLANNING</h3>
            <div class="separator_left"></div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="responsiveCal">
          <iframe class="cal" src="https://calendar.google.com/calendar/b/3/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=Europe%2FParis&amp;src=Y29udGFjdHZpdGFsbWFyY2hlQGdtYWlsLmNvbQ&amp;color=%2322AA99&amp;showTitle=0&amp;showNav=1&amp;showDate=1&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0" scrolling="yes"></iframe>
        </div>
      </div>

    </div>
  </section>
  <% if @on_top_pdf.nil? %>
  <% else %>
    <section id="pdf" class="new fix page">
      <div class="overlay"></div>
      <div class="container">
        <br>
        <br>
        <br>
        <div class="row">
          <div class="main_new">
            <div class="row on-top-pdf">
              <%= pdfjs_viewer pdf_url: @on_top_pdf.file, style: :full %>
            </div>
            <br>
            <br>
            <br>
          </div>
        </div>
      </div>
    </section>
  <% end %>
  <section class="new fix">
    <div class="overlay"></div>
    <div class="container">
      <br>
      <br>
      <br>
      <div class="row">
        <div class="main_new">
          <div class="head_title text-center row">
            <div class="col-xs-3">
              <i class='fas fa-chevron-left slid_prev text-white'></i>
            </div>
            <h3 class="col-xs-6 text-white">AUTRES GAZETTES</h3>
            <div class="col-xs-3">
              <i class='fa fas fa-chevron-right slid_next text-white'></i>
            </div>

          </div>
          <div class="row">
            <div class="pdf_slid text-center">
              <% if (@pdfs.empty? != true) && (@pdfs.nil? != true) %>
                <% @pdfs.each do |pdf| %>
                  <div class="pdf_item pdf-container row ">
                    <div class="test_authour article_text">
                      <h4 class="text-white to_fill_text"><%= pdf.title %></h4>
                    </div>
                    <div class="m-bottom-20">
                      <%= link_to "Consulter", pdfjs.full_path(file: pdf.file), class: "btn btn-primary", target: :_blank %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
          <br>
          <br>
          <br>
        </div>
      </div>
    </div>
  </section>
  <section id="form" class="about m-bottom-90 m-top-90 page">
    <div class="container">
      <div class="main_about">
        <div class="row">
          <div class="col-md-6">
            <div class="about_content">
              <br>
              <br>
              <h3>QUESTIONNAIRE</h3>
              <div class="separator_left"></div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6 to_fill_text">
            <% if @text_form != nil %>
              <div class="to_fill_text">
                <%= raw(@text_form.content) %>
              </div>
            <% else %>
              <div class="to_fill_text">
                Veuillez remplir le questionnaire disponible en cliquant sur le bouton ci-dessous s'il vous plaît.
              </div>
            <% end %>
            <br>
            <br>
            <br>
            <%= link_to "Google Form", @form.url, class: "btn btn-primary text-white", target: :_blank %>
            <br>
            <br>
          </div>
          <div class="col-xs-6">
            <% if @picture_form != nil %>
              <img class="join" <%= image_tag @picture_form.picture.to_s %>
            <% else %>
              <img class="join" <%= image_tag "image.jpg" %>
            <% end %>
          </div>
        </div>
        <% if current_user %>
          <div class="row">
            <div class="col-md-12 text-center m-top-40">
              <%= link_to "Supprimer mon compte", admin_destroy_user_path(current_user), class: "btn btn-danger", method: :delete, data: {confirm: "Êtes-vous sûrs de vouloir supprimer votre compte ?"} %>

            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
  <section id="photo-gallery" class="photo-gallery gallery page">
  </section>
</div>
</body>
<%= javascript_include_tag 'simple_user.js', 'data-turbolinks-track': 'reload' %>
<script>
    document.querySelector('#photo-gallery').appendChild(JGallery.create([
        <% @private_albums.each do |album| %>
        {
            title: '<%= album.title %>',

            items: [
                <% album.picture.each do |picture| %>
                {
                    url: '<%=picture.to_s %>',
                    thumbUrl: '<%=picture.to_s %>'
                }<% if picture != album.picture.last %>, <%end%><%end%>
            ]
        }<% if album != @private_albums.last %>, <%end%><%end%>]).getElement());
    <% if @pop_up != nil %>
    $(window).on('load', function () {
        $('#myModal').modal('show');
    });
    <% end %>
    $(document).ready(function () {
        $("#quitButton").click(function () {
            $("#quitModal").modal();
        });
    });

    function changeTitle() {
        var title = 'Vital\'Marche - Espace adhérent';
        var current_title = $(document).prop('title');
        if (current_title.indexOf('>>>') == -1) {
            setTimeout(changeTitle, 3000);
            $(document).prop('title', title);
        }
    }

    changeTitle();
</script>

app/views/user_space/main.html.erb
<head>
  <%= stylesheet_link_tag 'user_space', media: 'all', 'data-turbolinks-track': 'reload' %>
  <title>Espace adhérent du site Vital'Marche</title>
</head>
<div data-spy="scroll" data-target=".navbar-collapse">


  <div class="culmn">
    <%= render 'user_space/simple_user_space' %>
  </div>

  <footer id="footer" class="footer bg-black">
    <div class="container">
      <div class="row">
        <div class="main_footer text-center text-white p-top-40 p-bottom-30">
          <p class="wow fadeInRight" data-wow-duration="1s">
            <%= link_to "Vie privée", privacy_path, target: "_blank", data: {turbolinks: false} %> .
            Conçu avec
            <i class="fa fa-heart"></i>
            par
            <a target="_blank" href="https://github.com/lucaslamy">Lucas LAMY</a>
            2019.
          </p>
        </div>
      </div>
    </div>
  </footer>

</div>
</body>
</html>